"""Comprehensive protocol knowledge base — ALL known facts for brain initialization.

This is the canonical source of truth for the Links & Locks knowledge graph.
Every fact here becomes a Lock (deterministic, bypass inference).
Organized by domain, subdomain, and volatility tier.

Domains covered:
    - cardano: Cardano blockchain protocol, CIPs, Plutus, tooling
    - bitcoin: Bitcoin protocol, BIPs, opcodes, tooling
    - charms: Charms protocol on Bitcoin
    - bitcoinos: BitcoinOS / ZK verification layer
    - night_chain: Midnight / Night Chain privacy sidechain
    - cross_chain: Cross-chain bridging and interoperability
"""

from __future__ import annotations

from typing import Any

from autono.knowledge.types import VolatilityTier

# Type alias for structured protocol facts
ProtocolFact = dict  # {fact, domain, subdomain, answer, answer_type, source, tags, volatility}


# ============================================================================
# CARDANO
# ============================================================================

CARDANO_FACTS: list[ProtocolFact] = [
    # ---- Protocol Constants (PERMANENT) ------------------------------------
    {
        "fact": "Cardano slot duration is 1 second",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 1,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["slot", "timing", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano epoch length is 432,000 slots (5 days)",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 432000,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["epoch", "timing", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano average block time is approximately 20 seconds",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 20,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["block-time", "timing", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano k parameter (security parameter) is 2160",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 2160,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["security", "k-parameter", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano max block size is 90,112 bytes (88 KB)",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 90112,
        "answer_type": "integer",
        "source": "Cardano Protocol Parameters",
        "tags": ["block-size", "limit", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano max transaction size is 16,384 bytes",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 16384,
        "answer_type": "integer",
        "source": "Cardano Protocol Parameters",
        "tags": ["transaction-size", "limit", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano protocol magic for mainnet is 764824073",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 764824073,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["protocol-magic", "mainnet", "network"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano protocol magic for testnet is 1",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 1,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["protocol-magic", "testnet", "network"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano protocol magic for preprod is 1",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 1,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["protocol-magic", "preprod", "network"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano protocol magic for preview is 2",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 2,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["protocol-magic", "preview", "network"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano Shelley era started at epoch 208",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 208,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["shelley", "epoch", "era", "history"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano Byron era slot duration was 20 seconds",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 20,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["byron", "slot", "timing", "era"],
        "volatility": "permanent",
    },
    {
        "fact": "1 ADA = 1,000,000 Lovelace",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 1000000,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["ada", "lovelace", "conversion", "unit"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano minimum UTXO value is approximately 1 ADA (1,000,000 lovelace)",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 1000000,
        "answer_type": "lovelace",
        "source": "Cardano Protocol Parameters",
        "tags": ["utxo", "minimum", "lovelace", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano maximum supply is 45,000,000,000 ADA",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 45000000000,
        "answer_type": "integer",
        "source": "Cardano Specification",
        "tags": ["max-supply", "ada", "monetary-policy"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano treasury tax rate is 20% of rewards",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 0.20,
        "answer_type": "float",
        "source": "Cardano Protocol Parameters",
        "tags": ["treasury", "tax", "rewards", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano collateral percentage for Plutus scripts is 150%",
        "domain": "cardano",
        "subdomain": "protocol",
        "answer": 150,
        "answer_type": "integer",
        "source": "Cardano Protocol Parameters",
        "tags": ["collateral", "plutus", "script", "protocol-parameter"],
        "volatility": "permanent",
    },

    # ---- Address Types (PERMANENT) -----------------------------------------
    {
        "fact": "Cardano mainnet Shelley address prefix is addr1",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "addr1",
        "answer_type": "string",
        "source": "CIP-0019",
        "tags": ["address", "mainnet", "shelley", "bech32"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano testnet Shelley address prefix is addr_test1",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "addr_test1",
        "answer_type": "string",
        "source": "CIP-0019",
        "tags": ["address", "testnet", "shelley", "bech32"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano mainnet stake address prefix is stake1",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "stake1",
        "answer_type": "string",
        "source": "CIP-0019",
        "tags": ["address", "mainnet", "stake", "bech32"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano testnet stake address prefix is stake_test1",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "stake_test1",
        "answer_type": "string",
        "source": "CIP-0019",
        "tags": ["address", "testnet", "stake", "bech32"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano Byron mainnet addresses start with DdzFF (base58)",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "DdzFF",
        "answer_type": "string",
        "source": "Cardano Specification",
        "tags": ["address", "byron", "mainnet", "base58"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano Byron mainnet Icarus addresses start with Ae2td (base58)",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "Ae2td",
        "answer_type": "string",
        "source": "Cardano Specification",
        "tags": ["address", "byron", "icarus", "mainnet", "base58"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano mainnet script addresses start with addr1z",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "addr1z",
        "answer_type": "string",
        "source": "CIP-0019",
        "tags": ["address", "script", "mainnet", "bech32"],
        "volatility": "permanent",
    },
    {
        "fact": "Cardano testnet script addresses start with addr_test1z",
        "domain": "cardano",
        "subdomain": "address",
        "answer": "addr_test1z",
        "answer_type": "string",
        "source": "CIP-0019",
        "tags": ["address", "script", "testnet", "bech32"],
        "volatility": "permanent",
    },

    # ---- CIP Standards (STABLE) --------------------------------------------
    {
        "fact": "CIP-25 defines the NFT Metadata Standard using label 721",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "721",
        "answer_type": "integer",
        "source": "CIP-0025",
        "tags": ["nft", "metadata", "cip-25", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-26 defines Cardano Off-chain Metadata",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-26",
        "answer_type": "string",
        "source": "CIP-0026",
        "tags": ["off-chain", "metadata", "cip-26", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-27 defines CNFT Community Royalties standard",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-27",
        "answer_type": "string",
        "source": "CIP-0027",
        "tags": ["nft", "royalties", "cip-27", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-30 defines the Cardano dApp-Wallet Web Bridge",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-30",
        "answer_type": "string",
        "source": "CIP-0030",
        "tags": ["dapp", "wallet", "web-bridge", "cip-30", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-36 defines Catalyst Registration and Voting",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-36",
        "answer_type": "string",
        "source": "CIP-0036",
        "tags": ["catalyst", "voting", "registration", "cip-36", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-67 defines the Asset Name Label Standard (first 4 bytes = label)",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-67",
        "answer_type": "string",
        "source": "CIP-0067",
        "tags": ["asset-name", "label", "cip-67", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-68 defines the Datum Metadata Standard using reference tokens",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-68",
        "answer_type": "string",
        "source": "CIP-0068",
        "tags": ["datum", "metadata", "reference-token", "cip-68", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0019 defines Cardano Addresses using bech32 encoding",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-19",
        "answer_type": "string",
        "source": "CIP-0019",
        "tags": ["address", "bech32", "cip-19", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-1852 defines HD wallet key derivation with purpose 1852'",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": 1852,
        "answer_type": "integer",
        "source": "CIP-1852",
        "tags": ["wallet", "derivation", "hd-wallet", "cip-1852", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-1854 defines Multi-signatures HD wallets",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-1854",
        "answer_type": "string",
        "source": "CIP-1854",
        "tags": ["multisig", "hd-wallet", "cip-1854", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0002 defines the Coin Selection Algorithm for Cardano",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-2",
        "answer_type": "string",
        "source": "CIP-0002",
        "tags": ["coin-selection", "algorithm", "cip-2", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0005 defines Common Bech32 Prefixes for Cardano",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-5",
        "answer_type": "string",
        "source": "CIP-0005",
        "tags": ["bech32", "prefix", "cip-5", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0008 defines Message Signing for Cardano",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-8",
        "answer_type": "string",
        "source": "CIP-0008",
        "tags": ["message-signing", "cip-8", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0020 defines Transaction Message/Comment metadata",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-20",
        "answer_type": "string",
        "source": "CIP-0020",
        "tags": ["transaction", "message", "comment", "cip-20", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0086 defines NFT Metadata Update standard",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-86",
        "answer_type": "string",
        "source": "CIP-0086",
        "tags": ["nft", "metadata", "update", "cip-86", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0105 defines Conway Era Key Chains for HD Wallets",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-105",
        "answer_type": "string",
        "source": "CIP-0105",
        "tags": ["conway", "key-chain", "hd-wallet", "cip-105", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-0381 defines Plutus Support for Pairings over BLS12-381",
        "domain": "cardano",
        "subdomain": "cip",
        "answer": "CIP-381",
        "answer_type": "string",
        "source": "CIP-0381",
        "tags": ["plutus", "bls12-381", "cryptography", "cip-381", "standard"],
        "volatility": "stable",
    },

    # ---- Plutus / Smart Contracts (STABLE) ---------------------------------
    {
        "fact": "Plutus V1 was introduced in the Alonzo era at epoch 290",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": {"version": "PlutusV1", "era": "Alonzo", "epoch": 290},
        "answer_type": "json",
        "source": "Alonzo Hard Fork",
        "tags": ["plutus", "v1", "alonzo", "smart-contract", "era"],
        "volatility": "stable",
    },
    {
        "fact": "Plutus V2 was introduced in the Vasil era at epoch 365",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": {"version": "PlutusV2", "era": "Vasil", "epoch": 365},
        "answer_type": "json",
        "source": "Vasil Hard Fork",
        "tags": ["plutus", "v2", "vasil", "smart-contract", "era"],
        "volatility": "stable",
    },
    {
        "fact": "Plutus V3 was introduced in the Chang era at epoch 503",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": {"version": "PlutusV3", "era": "Chang", "epoch": 503},
        "answer_type": "json",
        "source": "Chang Hard Fork",
        "tags": ["plutus", "v3", "chang", "smart-contract", "era"],
        "volatility": "stable",
    },
    {
        "fact": "Plutus script purposes are Spend, Mint, Certify, Reward, Vote, and Propose",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": ["Spend", "Mint", "Certify", "Reward", "Vote", "Propose"],
        "answer_type": "json",
        "source": "Cardano Specification",
        "tags": ["plutus", "script-purpose", "smart-contract"],
        "volatility": "stable",
    },
    {
        "fact": "Plutus cost model uses CPU and memory units",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": {"units": ["cpu", "memory"]},
        "answer_type": "json",
        "source": "Cardano Specification",
        "tags": ["plutus", "cost-model", "execution-units"],
        "volatility": "stable",
    },
    {
        "fact": "Cardano script hash is 28-byte Blake2b-224",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": {"algorithm": "Blake2b-224", "bytes": 28},
        "answer_type": "json",
        "source": "Cardano Specification",
        "tags": ["script-hash", "blake2b", "cryptography"],
        "volatility": "stable",
    },
    {
        "fact": "Cardano datum hash is 32-byte Blake2b-256",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": {"algorithm": "Blake2b-256", "bytes": 32},
        "answer_type": "json",
        "source": "Cardano Specification",
        "tags": ["datum-hash", "blake2b", "cryptography"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-33 introduced reference scripts in the Vasil era",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": "CIP-33",
        "answer_type": "string",
        "source": "CIP-0033",
        "tags": ["reference-script", "vasil", "cip-33", "smart-contract"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-32 introduced inline datums in the Vasil era",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": "CIP-32",
        "answer_type": "string",
        "source": "CIP-0032",
        "tags": ["inline-datum", "vasil", "cip-32", "smart-contract"],
        "volatility": "stable",
    },
    {
        "fact": "CIP-31 introduced reference inputs in the Vasil era",
        "domain": "cardano",
        "subdomain": "plutus",
        "answer": "CIP-31",
        "answer_type": "string",
        "source": "CIP-0031",
        "tags": ["reference-input", "vasil", "cip-31", "smart-contract"],
        "volatility": "stable",
    },

    # ---- SDK / Tools (MODERATE) --------------------------------------------
    {
        "fact": "MeshJS is a JavaScript/TypeScript Cardano SDK",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "MeshJS",
        "answer_type": "string",
        "source": "https://meshjs.dev",
        "tags": ["meshjs", "javascript", "typescript", "sdk"],
        "volatility": "moderate",
    },
    {
        "fact": "cardano-cli is the official Cardano CLI tool",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "cardano-cli",
        "answer_type": "string",
        "source": "https://github.com/IntersectMBO/cardano-cli",
        "tags": ["cardano-cli", "cli", "tool"],
        "volatility": "moderate",
    },
    {
        "fact": "Opshin compiles Python to Plutus Core for Cardano smart contracts",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "opshin",
        "answer_type": "string",
        "source": "https://github.com/OpShin/opshin",
        "tags": ["opshin", "python", "smart-contract", "plutus", "compiler"],
        "volatility": "moderate",
    },
    {
        "fact": "Helios is a TypeScript Cardano smart contract toolkit",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "Helios",
        "answer_type": "string",
        "source": "https://github.com/Hyperion-BT/helios",
        "tags": ["helios", "typescript", "smart-contract", "toolkit"],
        "volatility": "moderate",
    },
    {
        "fact": "Aiken is a Cardano smart contract language with Rust-like syntax",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "Aiken",
        "answer_type": "string",
        "source": "https://aiken-lang.org",
        "tags": ["aiken", "rust", "smart-contract", "language"],
        "volatility": "moderate",
    },
    {
        "fact": "Lucid Evolution is a TypeScript SDK for Cardano transaction building",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "Lucid Evolution",
        "answer_type": "string",
        "source": "https://github.com/Anastasia-Labs/lucid-evolution",
        "tags": ["lucid", "lucid-evolution", "typescript", "sdk"],
        "volatility": "moderate",
    },
    {
        "fact": "Blockfrost is a Cardano REST API service",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "Blockfrost",
        "answer_type": "string",
        "source": "https://blockfrost.io",
        "tags": ["blockfrost", "api", "rest", "service"],
        "volatility": "moderate",
    },
    {
        "fact": "Koios is a decentralized Cardano API",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "Koios",
        "answer_type": "string",
        "source": "https://www.koios.rest",
        "tags": ["koios", "api", "decentralized", "service"],
        "volatility": "moderate",
    },
    {
        "fact": "Ogmios is a Cardano node WebSocket bridge",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "Ogmios",
        "answer_type": "string",
        "source": "https://ogmios.dev",
        "tags": ["ogmios", "websocket", "node", "bridge"],
        "volatility": "moderate",
    },
    {
        "fact": "cardano-db-sync is a PostgreSQL database for Cardano blockchain data",
        "domain": "cardano",
        "subdomain": "sdk",
        "answer": "cardano-db-sync",
        "answer_type": "string",
        "source": "https://github.com/IntersectMBO/cardano-db-sync",
        "tags": ["cardano-db-sync", "postgresql", "database", "indexer"],
        "volatility": "moderate",
    },

    # ---- API Endpoints (VOLATILE) ------------------------------------------
    {
        "fact": "Blockfrost mainnet API endpoint",
        "domain": "cardano",
        "subdomain": "api",
        "answer": "https://cardano-mainnet.blockfrost.io/api/v0",
        "answer_type": "url",
        "source": "https://blockfrost.io",
        "tags": ["blockfrost", "mainnet", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Blockfrost testnet API endpoint",
        "domain": "cardano",
        "subdomain": "api",
        "answer": "https://cardano-testnet.blockfrost.io/api/v0",
        "answer_type": "url",
        "source": "https://blockfrost.io",
        "tags": ["blockfrost", "testnet", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Blockfrost preview API endpoint",
        "domain": "cardano",
        "subdomain": "api",
        "answer": "https://cardano-preview.blockfrost.io/api/v0",
        "answer_type": "url",
        "source": "https://blockfrost.io",
        "tags": ["blockfrost", "preview", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Blockfrost preprod API endpoint",
        "domain": "cardano",
        "subdomain": "api",
        "answer": "https://cardano-preprod.blockfrost.io/api/v0",
        "answer_type": "url",
        "source": "https://blockfrost.io",
        "tags": ["blockfrost", "preprod", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Koios mainnet API endpoint",
        "domain": "cardano",
        "subdomain": "api",
        "answer": "https://api.koios.rest/api/v1",
        "answer_type": "url",
        "source": "https://www.koios.rest",
        "tags": ["koios", "mainnet", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Koios testnet API endpoint",
        "domain": "cardano",
        "subdomain": "api",
        "answer": "https://testnet.koios.rest/api/v1",
        "answer_type": "url",
        "source": "https://www.koios.rest",
        "tags": ["koios", "testnet", "api", "endpoint"],
        "volatility": "volatile",
    },

    # ---- Governance / Conway (STABLE) --------------------------------------
    {
        "fact": "Cardano Conway governance introduces DReps (Delegated Representatives)",
        "domain": "cardano",
        "subdomain": "governance",
        "answer": "DReps",
        "answer_type": "string",
        "source": "CIP-1694",
        "tags": ["governance", "drep", "conway", "delegation"],
        "volatility": "stable",
    },
    {
        "fact": "Cardano Conway governance includes a Constitutional Committee",
        "domain": "cardano",
        "subdomain": "governance",
        "answer": "Constitutional Committee",
        "answer_type": "string",
        "source": "CIP-1694",
        "tags": ["governance", "constitutional-committee", "conway"],
        "volatility": "stable",
    },
    {
        "fact": "Cardano Conway governance actions are NoConfidence, UpdateCommittee, NewConstitution, TreasuryWithdrawal, HardForkInitiation, ParameterChange, and InfoAction",
        "domain": "cardano",
        "subdomain": "governance",
        "answer": [
            "NoConfidence",
            "UpdateCommittee",
            "NewConstitution",
            "TreasuryWithdrawal",
            "HardForkInitiation",
            "ParameterChange",
            "InfoAction",
        ],
        "answer_type": "json",
        "source": "CIP-1694",
        "tags": ["governance", "action", "conway", "voting"],
        "volatility": "stable",
    },
    {
        "fact": "Cardano governance voting thresholds differ per governance action type",
        "domain": "cardano",
        "subdomain": "governance",
        "answer": "Thresholds vary by action type",
        "answer_type": "string",
        "source": "CIP-1694",
        "tags": ["governance", "voting", "threshold", "conway"],
        "volatility": "stable",
    },
]


# ============================================================================
# BITCOIN
# ============================================================================

BITCOIN_FACTS: list[ProtocolFact] = [
    # ---- Protocol Constants (PERMANENT) ------------------------------------
    {
        "fact": "1 BTC = 100,000,000 satoshis",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 100000000,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["btc", "satoshi", "conversion", "unit"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin maximum supply is 21,000,000 BTC",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 21000000,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["max-supply", "btc", "monetary-policy"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin target block time is 10 minutes (600 seconds)",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 600,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["block-time", "timing", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin block subsidy halving occurs every 210,000 blocks (approximately 4 years)",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 210000,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["halving", "subsidy", "monetary-policy"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin current block subsidy is 3.125 BTC (post April 2024 halving)",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 3.125,
        "answer_type": "float",
        "source": "Bitcoin Protocol",
        "tags": ["subsidy", "block-reward", "halving"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin next halving is approximately at block 1,050,000 (circa 2028)",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 1050000,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["halving", "future", "block-height"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin max block weight is 4,000,000 weight units",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 4000000,
        "answer_type": "integer",
        "source": "BIP-141",
        "tags": ["block-weight", "segwit", "limit", "protocol-parameter"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin max block size (legacy) is 1,000,000 bytes",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 1000000,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["block-size", "legacy", "limit"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin SegWit witness discount is 4x",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 4,
        "answer_type": "integer",
        "source": "BIP-141",
        "tags": ["segwit", "witness", "discount"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin dust limit for P2PKH outputs is 546 satoshis",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 546,
        "answer_type": "integer",
        "source": "Bitcoin Core",
        "tags": ["dust-limit", "p2pkh", "satoshi"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin dust limit for P2WPKH outputs is 294 satoshis",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 294,
        "answer_type": "integer",
        "source": "Bitcoin Core",
        "tags": ["dust-limit", "p2wpkh", "segwit", "satoshi"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin coinbase maturity requires 100 confirmations",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 100,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["coinbase", "maturity", "confirmations"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin difficulty adjustment occurs every 2016 blocks (approximately 2 weeks)",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 2016,
        "answer_type": "integer",
        "source": "Bitcoin Protocol",
        "tags": ["difficulty", "adjustment", "mining"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin SegWit activated at block 481,824 (August 2017)",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 481824,
        "answer_type": "integer",
        "source": "BIP-141",
        "tags": ["segwit", "activation", "block-height", "history"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin Taproot activated at block 709,632 (November 2021)",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": 709632,
        "answer_type": "integer",
        "source": "BIP-341",
        "tags": ["taproot", "activation", "block-height", "history"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin genesis block hash is 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        "domain": "bitcoin",
        "subdomain": "protocol",
        "answer": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        "answer_type": "hex",
        "source": "Bitcoin Protocol",
        "tags": ["genesis", "block-hash", "history"],
        "volatility": "permanent",
    },

    # ---- Address Types (PERMANENT) -----------------------------------------
    {
        "fact": "Bitcoin P2PKH (Legacy) addresses start with 1, use BIP-44 purpose 44'",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": {"prefix": "1", "type": "P2PKH", "bip": "BIP-44", "purpose": 44},
        "answer_type": "json",
        "source": "BIP-44",
        "tags": ["address", "p2pkh", "legacy", "bip-44"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin P2SH (SegWit wrapped) addresses start with 3, use BIP-49 purpose 49'",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": {"prefix": "3", "type": "P2SH", "bip": "BIP-49", "purpose": 49},
        "answer_type": "json",
        "source": "BIP-49",
        "tags": ["address", "p2sh", "segwit-wrapped", "bip-49"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin P2WPKH (Native SegWit) addresses start with bc1q, use BIP-84 purpose 84'",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": {"prefix": "bc1q", "type": "P2WPKH", "bip": "BIP-84", "purpose": 84},
        "answer_type": "json",
        "source": "BIP-84",
        "tags": ["address", "p2wpkh", "native-segwit", "bech32", "bip-84"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin P2TR (Taproot) addresses start with bc1p, use BIP-86 purpose 86'",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": {"prefix": "bc1p", "type": "P2TR", "bip": "BIP-86", "purpose": 86},
        "answer_type": "json",
        "source": "BIP-86",
        "tags": ["address", "p2tr", "taproot", "bech32m", "bip-86"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin testnet bech32 addresses start with tb1",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": "tb1",
        "answer_type": "string",
        "source": "BIP-173",
        "tags": ["address", "testnet", "bech32"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin testnet legacy addresses start with m or n",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": ["m", "n"],
        "answer_type": "json",
        "source": "Bitcoin Protocol",
        "tags": ["address", "testnet", "legacy"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin testnet P2SH addresses start with 2",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": "2",
        "answer_type": "string",
        "source": "Bitcoin Protocol",
        "tags": ["address", "testnet", "p2sh"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin coin type for mainnet is 0",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": 0,
        "answer_type": "integer",
        "source": "SLIP-0044",
        "tags": ["coin-type", "mainnet", "derivation"],
        "volatility": "permanent",
    },
    {
        "fact": "Bitcoin coin type for testnet is 1",
        "domain": "bitcoin",
        "subdomain": "address",
        "answer": 1,
        "answer_type": "integer",
        "source": "SLIP-0044",
        "tags": ["coin-type", "testnet", "derivation"],
        "volatility": "permanent",
    },

    # ---- BIP Standards (STABLE) --------------------------------------------
    {
        "fact": "BIP-32 defines Hierarchical Deterministic Wallets",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-32",
        "answer_type": "string",
        "source": "BIP-0032",
        "tags": ["bip-32", "hd-wallet", "hierarchical-deterministic", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-39 defines Mnemonic code for generating deterministic keys",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-39",
        "answer_type": "string",
        "source": "BIP-0039",
        "tags": ["bip-39", "mnemonic", "seed-phrase", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-44 defines Multi-Account Hierarchy for Deterministic Wallets",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-44",
        "answer_type": "string",
        "source": "BIP-0044",
        "tags": ["bip-44", "multi-account", "hd-wallet", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-49 defines derivation scheme for P2WPKH-nested-in-P2SH",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-49",
        "answer_type": "string",
        "source": "BIP-0049",
        "tags": ["bip-49", "p2wpkh", "p2sh", "derivation", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-84 defines derivation scheme for P2WPKH native SegWit",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-84",
        "answer_type": "string",
        "source": "BIP-0084",
        "tags": ["bip-84", "p2wpkh", "native-segwit", "derivation", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-86 defines derivation scheme for P2TR Taproot",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-86",
        "answer_type": "string",
        "source": "BIP-0086",
        "tags": ["bip-86", "p2tr", "taproot", "derivation", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-141 defines Segregated Witness consensus rules",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-141",
        "answer_type": "string",
        "source": "BIP-0141",
        "tags": ["bip-141", "segwit", "consensus", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-143 defines transaction signature verification for SegWit",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-143",
        "answer_type": "string",
        "source": "BIP-0143",
        "tags": ["bip-143", "segwit", "signature", "verification", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-174 defines Partially Signed Bitcoin Transactions (PSBT)",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-174",
        "answer_type": "string",
        "source": "BIP-0174",
        "tags": ["bip-174", "psbt", "transaction", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-340 defines Schnorr Signatures for secp256k1",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-340",
        "answer_type": "string",
        "source": "BIP-0340",
        "tags": ["bip-340", "schnorr", "signature", "secp256k1", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-341 defines Taproot SegWit version 1 spending rules",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-341",
        "answer_type": "string",
        "source": "BIP-0341",
        "tags": ["bip-341", "taproot", "segwit-v1", "spending-rules", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-342 defines validation of Taproot Scripts",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-342",
        "answer_type": "string",
        "source": "BIP-0342",
        "tags": ["bip-342", "taproot", "tapscript", "validation", "standard"],
        "volatility": "stable",
    },
    {
        "fact": "BIP-370 defines PSBT Version 2",
        "domain": "bitcoin",
        "subdomain": "bip",
        "answer": "BIP-370",
        "answer_type": "string",
        "source": "BIP-0370",
        "tags": ["bip-370", "psbt", "v2", "transaction", "standard"],
        "volatility": "stable",
    },

    # ---- Script / Opcodes (PERMANENT) --------------------------------------
    {
        "fact": "OP_RETURN (0x6a) creates provably unspendable output for data embedding",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_RETURN", "hex": "0x6a"},
        "answer_type": "json",
        "source": "Bitcoin Script",
        "tags": ["opcode", "op-return", "data-embedding", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "OP_CHECKSIG (0xac) verifies a single signature",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_CHECKSIG", "hex": "0xac"},
        "answer_type": "json",
        "source": "Bitcoin Script",
        "tags": ["opcode", "op-checksig", "signature", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "OP_CHECKMULTISIG (0xae) verifies multiple signatures",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_CHECKMULTISIG", "hex": "0xae"},
        "answer_type": "json",
        "source": "Bitcoin Script",
        "tags": ["opcode", "op-checkmultisig", "multisig", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "OP_HASH160 (0xa9) performs SHA256 then RIPEMD160",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_HASH160", "hex": "0xa9", "operation": "SHA256 + RIPEMD160"},
        "answer_type": "json",
        "source": "Bitcoin Script",
        "tags": ["opcode", "op-hash160", "hash", "cryptography", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "OP_EQUAL (0x87) checks equality of top two stack items",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_EQUAL", "hex": "0x87"},
        "answer_type": "json",
        "source": "Bitcoin Script",
        "tags": ["opcode", "op-equal", "comparison", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "OP_DUP (0x76) duplicates the top stack item",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_DUP", "hex": "0x76"},
        "answer_type": "json",
        "source": "Bitcoin Script",
        "tags": ["opcode", "op-dup", "stack", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "OP_CHECKLOCKTIMEVERIFY (0xb1) enforces absolute timelock",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_CHECKLOCKTIMEVERIFY", "hex": "0xb1"},
        "answer_type": "json",
        "source": "BIP-65",
        "tags": ["opcode", "op-cltv", "timelock", "absolute", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "OP_CHECKSEQUENCEVERIFY (0xb2) enforces relative timelock",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": {"opcode": "OP_CHECKSEQUENCEVERIFY", "hex": "0xb2"},
        "answer_type": "json",
        "source": "BIP-112",
        "tags": ["opcode", "op-csv", "timelock", "relative", "script"],
        "volatility": "permanent",
    },
    {
        "fact": "Tapscript uses witness version 1",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": 1,
        "answer_type": "integer",
        "source": "BIP-341",
        "tags": ["tapscript", "witness-version", "taproot"],
        "volatility": "permanent",
    },
    {
        "fact": "Schnorr signature size is 64 bytes",
        "domain": "bitcoin",
        "subdomain": "script",
        "answer": 64,
        "answer_type": "integer",
        "source": "BIP-340",
        "tags": ["schnorr", "signature", "size", "bytes"],
        "volatility": "permanent",
    },

    # ---- APIs (VOLATILE) ---------------------------------------------------
    {
        "fact": "Blockstream mainnet API endpoint",
        "domain": "bitcoin",
        "subdomain": "api",
        "answer": "https://blockstream.info/api",
        "answer_type": "url",
        "source": "https://blockstream.info",
        "tags": ["blockstream", "mainnet", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Blockstream testnet API endpoint",
        "domain": "bitcoin",
        "subdomain": "api",
        "answer": "https://blockstream.info/testnet/api",
        "answer_type": "url",
        "source": "https://blockstream.info",
        "tags": ["blockstream", "testnet", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Mempool.space mainnet API endpoint",
        "domain": "bitcoin",
        "subdomain": "api",
        "answer": "https://mempool.space/api",
        "answer_type": "url",
        "source": "https://mempool.space",
        "tags": ["mempool-space", "mainnet", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Mempool.space testnet API endpoint",
        "domain": "bitcoin",
        "subdomain": "api",
        "answer": "https://mempool.space/testnet/api",
        "answer_type": "url",
        "source": "https://mempool.space",
        "tags": ["mempool-space", "testnet", "api", "endpoint"],
        "volatility": "volatile",
    },
    {
        "fact": "Bitcoin Core RPC default port is 8332 (mainnet), 18332 (testnet), 18443 (regtest)",
        "domain": "bitcoin",
        "subdomain": "api",
        "answer": {"mainnet": 8332, "testnet": 18332, "regtest": 18443},
        "answer_type": "json",
        "source": "Bitcoin Core",
        "tags": ["rpc", "port", "bitcoin-core", "network"],
        "volatility": "volatile",
    },
]


# ============================================================================
# CHARMS
# ============================================================================

CHARMS_FACTS: list[ProtocolFact] = [
    # ---- Core Protocol (STABLE) --------------------------------------------
    {
        "fact": "Charms are entries of mapping app->data on top of a Bitcoin UTXO",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": "app->data mapping on Bitcoin UTXO",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["charms", "utxo", "bitcoin", "definition"],
        "volatility": "stable",
    },
    {
        "fact": "Charms on-chain format: OP_RETURN OP_PUSH 'spell' OP_PUSH CBOR(NormalizedSpell, Groth16Proof)",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": "OP_RETURN OP_PUSH 'spell' OP_PUSH CBOR(NormalizedSpell, Groth16Proof)",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["charms", "op-return", "cbor", "groth16", "on-chain"],
        "volatility": "stable",
    },
    {
        "fact": "Charms app tag 'n' represents NFT and 't' represents fungible Token",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": {"n": "NFT", "t": "Token"},
        "answer_type": "json",
        "source": "Charms Protocol",
        "tags": ["charms", "app-tag", "nft", "token"],
        "volatility": "stable",
    },
    {
        "fact": "Charms app identity is 32 bytes",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": 32,
        "answer_type": "integer",
        "source": "Charms Protocol",
        "tags": ["charms", "app-identity", "bytes"],
        "volatility": "stable",
    },
    {
        "fact": "Charms apps are written in Rust with app_contract as the entry point function",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": "app_contract",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["charms", "rust", "entry-point", "app-contract"],
        "volatility": "stable",
    },
    {
        "fact": "Charms scaffold command is 'charms app new <name>'",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": "charms app new <name>",
        "answer_type": "string",
        "source": "Charms CLI",
        "tags": ["charms", "scaffold", "cli", "command"],
        "volatility": "stable",
    },
    {
        "fact": "Charms spell validity requires parseable + logically consistent + valid ZK proof",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": ["parseable", "logically consistent", "valid ZK proof"],
        "answer_type": "json",
        "source": "Charms Protocol",
        "tags": ["charms", "spell", "validity", "zk-proof"],
        "volatility": "stable",
    },
    {
        "fact": "Charms requires Bitcoin Core v28.0+ with testnet4",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": {"bitcoin_core_version": "v28.0+", "network": "testnet4"},
        "answer_type": "json",
        "source": "Charms Protocol",
        "tags": ["charms", "bitcoin-core", "testnet4", "requirement"],
        "volatility": "stable",
    },
    {
        "fact": "Charms NormalizedSpell contains app_public_inputs and tx (ins, outs, coins)",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": {"fields": ["app_public_inputs", "tx"], "tx_fields": ["ins", "outs", "coins"]},
        "answer_type": "json",
        "source": "Charms Protocol",
        "tags": ["charms", "normalized-spell", "structure"],
        "volatility": "stable",
    },
    {
        "fact": "Charms spell transactions have exactly 2 outputs: actual output + OP_RETURN",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": 2,
        "answer_type": "integer",
        "source": "Charms Protocol",
        "tags": ["charms", "transaction", "output", "op-return"],
        "volatility": "stable",
    },
    {
        "fact": "Charms uses client-side validation with Groth16 proofs",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": "Groth16",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["charms", "groth16", "zk-proof", "client-side-validation"],
        "volatility": "stable",
    },
    {
        "fact": "Charms node validates spells before adding them to its index",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": "Validate before index",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["charms", "node", "validation", "index"],
        "volatility": "stable",
    },
    {
        "fact": "Charms tick is a unique lowercase string identifier for fungible tokens",
        "domain": "charms",
        "subdomain": "protocol",
        "answer": "lowercase string identifier",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["charms", "tick", "fungible-token", "identifier"],
        "volatility": "stable",
    },

    # ---- CLI Commands (MODERATE) -------------------------------------------
    {
        "fact": "charms app new <name>: scaffold a new Charms app",
        "domain": "charms",
        "subdomain": "cli",
        "answer": "charms app new <name>",
        "answer_type": "string",
        "source": "Charms CLI",
        "tags": ["charms", "cli", "scaffold", "new-app"],
        "volatility": "moderate",
    },
    {
        "fact": "charms app build: compile a Charms app to WASM",
        "domain": "charms",
        "subdomain": "cli",
        "answer": "charms app build",
        "answer_type": "string",
        "source": "Charms CLI",
        "tags": ["charms", "cli", "build", "wasm", "compile"],
        "volatility": "moderate",
    },
    {
        "fact": "charms spell create: create a new Charms spell",
        "domain": "charms",
        "subdomain": "cli",
        "answer": "charms spell create",
        "answer_type": "string",
        "source": "Charms CLI",
        "tags": ["charms", "cli", "spell", "create"],
        "volatility": "moderate",
    },
    {
        "fact": "charms spell prove: generate ZK proof for a Charms spell",
        "domain": "charms",
        "subdomain": "cli",
        "answer": "charms spell prove",
        "answer_type": "string",
        "source": "Charms CLI",
        "tags": ["charms", "cli", "spell", "prove", "zk-proof"],
        "volatility": "moderate",
    },
    {
        "fact": "charms spell cast: submit a Charms spell transaction",
        "domain": "charms",
        "subdomain": "cli",
        "answer": "charms spell cast",
        "answer_type": "string",
        "source": "Charms CLI",
        "tags": ["charms", "cli", "spell", "cast", "submit"],
        "volatility": "moderate",
    },
]


# ============================================================================
# BITCOINOS
# ============================================================================

BITCOINOS_FACTS: list[ProtocolFact] = [
    {
        "fact": "BitcoinOS first verified a ZK proof on Bitcoin mainnet at Block 853,626 (July 2024)",
        "domain": "bitcoinos",
        "subdomain": "protocol",
        "answer": {"block": 853626, "date": "July 2024"},
        "answer_type": "json",
        "source": "BitcoinOS",
        "tags": ["bitcoinos", "zk-proof", "mainnet", "milestone", "history"],
        "volatility": "stable",
    },
    {
        "fact": "Grail Bridge provides trustless cross-chain bridging via ZK proofs",
        "domain": "bitcoinos",
        "subdomain": "protocol",
        "answer": "Grail Bridge",
        "answer_type": "string",
        "source": "BitcoinOS",
        "tags": ["bitcoinos", "grail-bridge", "cross-chain", "zk-proof", "bridge"],
        "volatility": "stable",
    },
    {
        "fact": "BitSNARK is a ZK verification VM for Bitcoin",
        "domain": "bitcoinos",
        "subdomain": "protocol",
        "answer": "BitSNARK",
        "answer_type": "string",
        "source": "BitcoinOS",
        "tags": ["bitcoinos", "bitsnark", "zk-verification", "vm"],
        "volatility": "stable",
    },
    {
        "fact": "zkBTC is a 1:1 BTC-backed programmable token on BitcoinOS",
        "domain": "bitcoinos",
        "subdomain": "protocol",
        "answer": "zkBTC",
        "answer_type": "string",
        "source": "BitcoinOS",
        "tags": ["bitcoinos", "zkbtc", "programmable-token", "btc-backed"],
        "volatility": "stable",
    },
    {
        "fact": "MerkleMesh is rollup infrastructure on Bitcoin from BitcoinOS",
        "domain": "bitcoinos",
        "subdomain": "protocol",
        "answer": "MerkleMesh",
        "answer_type": "string",
        "source": "BitcoinOS",
        "tags": ["bitcoinos", "merklemesh", "rollup", "infrastructure"],
        "volatility": "stable",
    },
    {
        "fact": "BitcoinOS uses a 1/n honest verifier trust model (single honest verifier guarantees integrity)",
        "domain": "bitcoinos",
        "subdomain": "protocol",
        "answer": "1/n honest verifier",
        "answer_type": "string",
        "source": "BitcoinOS",
        "tags": ["bitcoinos", "trust-model", "honest-verifier", "security"],
        "volatility": "stable",
    },
    {
        "fact": "Grail Bridge locks BTC in Taproot address, verifies via ZK, then mints on L2",
        "domain": "bitcoinos",
        "subdomain": "protocol",
        "answer": "Lock BTC in Taproot -> ZK verify -> Mint on L2",
        "answer_type": "string",
        "source": "BitcoinOS",
        "tags": ["bitcoinos", "grail-bridge", "taproot", "zk-proof", "l2", "flow"],
        "volatility": "stable",
    },
]


# ============================================================================
# MIDNIGHT / NIGHT CHAIN
# ============================================================================

NIGHT_CHAIN_FACTS: list[ProtocolFact] = [
    {
        "fact": "Midnight is a privacy-preserving sidechain from IOG",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "Midnight",
        "answer_type": "string",
        "source": "IOG / Midnight",
        "tags": ["midnight", "privacy", "sidechain", "iog"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight uses Compact language for ZK-powered smart contracts",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "Compact",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "compact", "smart-contract", "zk-proof", "language"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight uses Ed25519 keypairs for cryptographic operations",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "Ed25519",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "ed25519", "keypair", "cryptography"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight addresses use night1 prefix with bech32 encoding",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "night1",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "address", "prefix", "bech32"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight uses AES-256-GCM encryption with PBKDF2 key derivation (100,000 iterations)",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": {"encryption": "AES-256-GCM", "kdf": "PBKDF2", "iterations": 100000},
        "answer_type": "json",
        "source": "Midnight",
        "tags": ["midnight", "aes-256-gcm", "pbkdf2", "encryption", "key-derivation"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight uses zero-knowledge proofs for data protection",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "Zero-knowledge proofs",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "zk-proof", "privacy", "data-protection"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight supports selective disclosure: prove properties without revealing data",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "Selective disclosure",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "selective-disclosure", "privacy", "zk-proof"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight DarkShield nodes handle private state",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "DarkShield",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "darkshield", "node", "private-state"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight native utility token is DUST",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "DUST",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "dust", "token", "native"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight is built using IOG's partner chains framework",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "Partner chains framework",
        "answer_type": "string",
        "source": "IOG",
        "tags": ["midnight", "iog", "partner-chains", "framework"],
        "volatility": "stable",
    },
    {
        "fact": "Midnight Compact language features public/private state distinction",
        "domain": "night_chain",
        "subdomain": "protocol",
        "answer": "public/private state distinction",
        "answer_type": "string",
        "source": "Midnight",
        "tags": ["midnight", "compact", "public-state", "private-state", "language"],
        "volatility": "stable",
    },
]


# ============================================================================
# CROSS-CHAIN
# ============================================================================

CROSS_CHAIN_FACTS: list[ProtocolFact] = [
    {
        "fact": "Cardano and Bitcoin interop via Charms uses native materialization, no wrapped tokens",
        "domain": "cross_chain",
        "subdomain": "bridge",
        "answer": "Native materialization, no wrapped tokens",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["cross-chain", "cardano", "bitcoin", "charms", "native"],
        "volatility": "stable",
    },
    {
        "fact": "Bitcoin to L2 via Grail Bridge: lock BTC then mint zkBTC",
        "domain": "cross_chain",
        "subdomain": "bridge",
        "answer": "Lock BTC -> Mint zkBTC",
        "answer_type": "string",
        "source": "BitcoinOS",
        "tags": ["cross-chain", "bitcoin", "l2", "grail-bridge", "zkbtc"],
        "volatility": "stable",
    },
    {
        "fact": "Charms bridgeless design: tokens appear natively on each chain",
        "domain": "cross_chain",
        "subdomain": "bridge",
        "answer": "Bridgeless native token appearance",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["cross-chain", "charms", "bridgeless", "native-token"],
        "volatility": "stable",
    },
    {
        "fact": "Bitcoin, Cardano, and Night Chain all share UTXO model compatibility",
        "domain": "cross_chain",
        "subdomain": "interop",
        "answer": ["Bitcoin", "Cardano", "Night Chain"],
        "answer_type": "json",
        "source": "Protocol Architecture",
        "tags": ["cross-chain", "utxo", "compatibility", "bitcoin", "cardano", "night-chain"],
        "volatility": "stable",
    },
    {
        "fact": "Cross-chain spells are the coordination primitive between chains",
        "domain": "cross_chain",
        "subdomain": "interop",
        "answer": "Cross-chain spells",
        "answer_type": "string",
        "source": "Charms Protocol",
        "tags": ["cross-chain", "spell", "coordination", "primitive"],
        "volatility": "stable",
    },
    {
        "fact": "ZK proofs serve as the universal verification layer across chains",
        "domain": "cross_chain",
        "subdomain": "interop",
        "answer": "ZK proofs as universal verification",
        "answer_type": "string",
        "source": "Protocol Architecture",
        "tags": ["cross-chain", "zk-proof", "verification", "universal"],
        "volatility": "stable",
    },
]


# ============================================================================
# MASTER REGISTRY
# ============================================================================

ALL_PROTOCOL_FACTS: list[ProtocolFact] = (
    CARDANO_FACTS
    + BITCOIN_FACTS
    + CHARMS_FACTS
    + BITCOINOS_FACTS
    + NIGHT_CHAIN_FACTS
    + CROSS_CHAIN_FACTS
)

FACTS_BY_DOMAIN: dict[str, list[ProtocolFact]] = {
    "cardano": CARDANO_FACTS,
    "bitcoin": BITCOIN_FACTS,
    "charms": CHARMS_FACTS,
    "bitcoinos": BITCOINOS_FACTS,
    "night_chain": NIGHT_CHAIN_FACTS,
    "cross_chain": CROSS_CHAIN_FACTS,
}


def get_facts_by_volatility(tier: VolatilityTier) -> list[ProtocolFact]:
    """Return all protocol facts matching the given volatility tier.

    Args:
        tier: The VolatilityTier to filter on.

    Returns:
        List of ProtocolFact dicts whose volatility matches the tier value.
    """
    tier_value = tier.value if isinstance(tier, VolatilityTier) else tier
    return [f for f in ALL_PROTOCOL_FACTS if f["volatility"] == tier_value]


def get_facts_count() -> dict[str, int]:
    """Return a breakdown of fact counts by domain and a total.

    Returns:
        Dict mapping domain names to their fact count, plus a "total" key.
    """
    counts: dict[str, int] = {
        domain: len(facts) for domain, facts in FACTS_BY_DOMAIN.items()
    }
    counts["total"] = len(ALL_PROTOCOL_FACTS)
    return counts


def get_facts_by_subdomain(domain: str, subdomain: str) -> list[ProtocolFact]:
    """Return facts filtered by both domain and subdomain.

    Args:
        domain: The domain to filter on (e.g. "cardano", "bitcoin").
        subdomain: The subdomain to filter on (e.g. "protocol", "cip", "address").

    Returns:
        List of matching ProtocolFact dicts.
    """
    domain_facts = FACTS_BY_DOMAIN.get(domain, [])
    return [f for f in domain_facts if f["subdomain"] == subdomain]


def get_facts_by_tag(tag: str) -> list[ProtocolFact]:
    """Return all facts that contain the given tag.

    Args:
        tag: The tag string to search for (e.g. "nft", "zk-proof", "address").

    Returns:
        List of matching ProtocolFact dicts.
    """
    return [f for f in ALL_PROTOCOL_FACTS if tag in f.get("tags", [])]
